name: Build and push cngrok to docker hub.

on:
  push:
    branches: [ main ]
    paths: [ src/** ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - id: Build&Push
      name: Build and push Docker images
      uses: docker/build-push-action@v2.1.0
      with:
        push: true
        tags: wimdegroot/cngrok:latest
        secrets: |
          GIT_AUTH_TOKEN=${{ secrets.DOCKER_HUB_TOKEN }}

